### ISSUE TITLE
Examples of usage?

### ISSUE THREAD

**Issue by silvenon** [bloodyowl/react-higher-event#1]
Cool library! It would be nice to see a few example scenarios when it would be useful.

**Comment by bloodyowl** [comment]
There's already one in the repository https://github.com/bloodyowl/react-higher-event/tree/master/examples/dropdown

Might add a modal scenario later though.

**Comment by naholyr** [comment]
In the given example I don't get how the whole thing is useful. It feels like you can get the same result by simply dropping ReactHigherEvent\* components. It could be nice to have examples explaining really how it should be useful.

**Comment by bloodyowl** [comment]
Thanks for the feedback, I'll add an explanation about the synthetic event system and how it solves issues with `stopPropagation` 👍

**Comment by silvenon** [comment]
Sounds awesome! I've been having so many issues with propagation.
