### ISSUE TITLE
Add ability to proxy events from within an iframe to react higher event container

### ISSUE THREAD

**Issue by acusti** [bloodyowl/react-higher-event#2]
Using iframes in React is powerful (for fully scoped / safe rendering of different things, like for any kind of editor, where the editor contents can be scoped to an iframe, or for a preview pane), and consistently getting better (we use the [react frame component](https://developer.zendesk.com/blog/rendering-to-iframes-in-react), and lots of components in the open source community have been adapted to work across iframes, like [react-draggable](https://github.com/mzabriskie/react-draggable/pull/180) and [react-dnd](https://github.com/gaearon/react-dnd-html5-backend/pull/9)). However, there are lots of hard problems it can create for the wide span of UI features that get tripped up by multiple HTML documents that can listen to events.

This component could be a really great solution for that problem if it had some kind of a proxy component that you could include inside an iframe that would proxy and events to any other event handlers in the app that were registered via the `ReactHigherEvent` component.

**Comment by bloodyowl** [comment]
I'd like very much to have support for this, although I find the `Proxy` component to be a bit confusing as an API.

What are the main use-cases you have in mind?

**Comment by acusti** [comment]
I completed missed your comment! Sorry about that, and thanks for replying.

The main use case I have in mind is for editor apps where you want to scope the editor (along with behavior, styles, selections) to an iframe rendered by the same React / Flux context as the rest of your app. In such an app, the `ReactHigherEvent` approach breaks down when the browser’s focus is in the iframe, because the `ReactHigherEventContainer`’s `<div>` won’t be the target of any events triggered within the iframe.

The `Proxy` component can be used to wrap the contents of the iframe with a `<div>` to capture events and then invoke the event handlers registered from any `ReactHigherEvent` components. My current use case (using [react-frame-component](https://github.com/ryanseddon/react-frame-component), imported here as `Frame`) looks like:

``` js
<Frame>
  <ReactHigherEventProxy>
    <h1>My example editor</h1>
    <EditorContents />
  </ReactHigherEventProxy>
</Frame>
```

Not sure how easy it is to follow, but [the tests](https://github.com/bloodyowl/react-higher-event/pull/3/files#diff-5cda64d0325f1ce091c04cc4c99f3533R216) illustrate the use case more thoroughly. It shows how you can have an iframe with a `Proxy` inside it, along with a `Receiver` outside of the iframe that will then receive click events from a DOM element inside the Proxy inside the iframe.

**Comment by acusti** [comment]
Any more ideas on how you’d like to see this implemented in ReactHigherEvent? I’d be happy to make changes or help in any way. Currently we’re just using our fork, but would love to be able to switch back to this one.

**Comment by acusti** [comment]
Thought I’d check in again to see if you had any further ideas about how you’d like to implement something like the `ReactHigherEventProxy`.
