### ISSUE TITLE
Accepting (only one) children seems useless

### ISSUE THREAD

**Issue by MoOx** [bloodyowl/react-higher-event#4]
Currently docs say to use this module like that
```js
   render() {
    const { props, state } = this

    return (
      <View>
        <ReactHigherEvent onClick={ this.handleClose }>
          <Button onClick={ this.handleOpen }>...</Button>
        </ReactHigherEvent>
```

But I feel like it's not really useful to use a child.

Am I drunk thinking that accepting a child is useless? (btw, why ONE only?)

I can use this module like this

```js
   render() {
    const { props, state } = this

    return (
      <View>
        <ReactHigherEvent onClick={ this.handleClose }>
          <View />
        </ReactHigherEvent>
        <Button onClick={ this.handleOpen }>...</Button>
```

It works the same.

From what I just read in the code, children is not really used so I guess we could remove it so we can use it like this

```js
   render() {
    const { props, state } = this

    return (
      <View>
        <ReactHigherEvent onClick={ this.handleClose } />
        <Button onClick={ this.handleOpen }>...</Button>
```

It will works the same and will be even more easy to add, as you don't have to change your code, just add some.

Thoughts?

**Comment by bloodyowl** [comment]
The idea is just to use the child you provide without adding an HTML element in the way.

You can do 

```js
<ReactHigherEvent>
  <div>
    {/* children */}
  </div>
</ReactHigherEvent>

**Comment by MoOx** [comment]
Sorry I was totally drunk. I missed on huge thing and will make a PR to improve the README.
